MLIA-756 Fix Vela bug in MLIA caused by numpy
Set a constraint for numpy in MLIA to be < 1.24. This is needed to fix
the temporary issue that Numpy is causing in Vela 3.6
(i.e. "AttributeError: module 'numpy' has no attribute 'bool'")

Change-Id: Ie9c99a7a328b5db4c89bccc9429ab93d6a88fe9e